default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: non_carbo
  host: localhost              
  password:

production:
  <<: *default
  database: non_carbo_production   

staging:
  <<: *default
  database: non_carbo_production   

development:
  <<: *default
  database: non_carbo_development   

test:
  <<: *default
  database: non_carbo_test   
